In [ ]:
#安裝順序conda install numpy>scipy>matplotlib>seaborn
import scipy
import matplotlib
import numpy 
import seaborn
import pandas
import bokeh

In [41]:
#dtype参数         #多少维度ndmin 
#size陣列元素總數  #shape (n*m)陣列形狀
#itemsize 陣列元素佔用的位元組數
#nbytes 整個陣列佔用的位元組數
import numpy as np 
a = np.array([1,  2,  3], dtype = complex,ndmin =  2)  
print (a)
print(type(a))
print(a.dtype) #dtype参数
print(a.size) #size陣列元素總數
print(a.shape) #shape (n*m)陣列形狀
print(a.itemsize) #itemsize 陣列元素佔用的位元組數
print(a.ndim) #多少维度ndmin 
print(a.nbytes) #nbytes 整個陣列佔用的位元組數
del a

[[1.+0.j 2.+0.j 3.+0.j]]
<class 'numpy.ndarray'>
complex128
3
(1, 3)
16
2
48


In [44]:
#使用清單元組建立一維陣列
import numpy as np 
a = np.array([1,2,3,4,5])
b = np.array((1,2,3,4,5))
print(type(a))
print(type(b))
print(a[0],a[1],a[2],a[3],a[4])
b[0]=5
print(b)
b[4]=0
print(b)
del a,b

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
1 2 3 4 5
[5 2 3 4 5]
[5 2 3 4 0]


In [45]:
#指定元素型態陣列
a = np.array([1, 2, 3, 4, 5], int)
b = np.array((1, 2, 3, 4, 5), dtype=float)
print(a)
print(b)
del a,b

[1 2 3 4 5]
[1. 2. 3. 4. 5.]


In [46]:
a = np.array([[1,2,3],[4,5,6]])
b = np.zeros_like(a)
print(b)
c = np.ones_like(a)
print(c)
del a,b,c

[[0 0 0]
 [0 0 0]]
[[1 1 1]
 [1 1 1]]


In [47]:
#陣列維度轉換numpy.reshape()
#ndarray.reshape 通常返回的是非拷貝副本，
#即改變返回後數組的元素，原數組對應元素的值也會改變。
a = np.arange(16)
print(a)
b = a.reshape((4,4))
print(b)
b[0]=100
print(a) #淺複製
c = np.array(range(10), float)
print(c)
d = c.reshape((5,2))
print(d)
del a,b,c,d

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[100 100 100 100   4   5   6   7   8   9  10  11  12  13  14  15]
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
[[0. 1.]
 [2. 3.]
 [4. 5.]
 [6. 7.]
 [8. 9.]]


In [49]:
#將陣列儲存成npy檔案
a = np.arange(10)
outputfile = "Example.npy"
with open(outputfile, 'wb') as fp:
    np.save(fp, a)
#將陣列儲存成out檔案
b = np.array([[1,2,3],[4,5,6]])
outputfile = "Example.out"
np.savetxt(outputfile, b, delimiter=',')
#讀取npy
outputfile = "Example.npy"
with open(outputfile, 'rb') as fp:
    a = np.load(fp)
print(a)
#讀取out
outputfile = "Example.out"
np.loadtxt(outputfile,delimiter=',')
print(b)
del a,b

[0 1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]]


In [64]:
#向量與純量四則運算
a = np.array([1,2,3])
print("v=" +str(a))
s = 5
print("s=" + str(s))
b=a+s
print("a+s=" + str(b))
b=a-s
print("a-s=" + str(b))
b=a*s
print("a*s=" + str(b))
b=a/s
print("a/s=" + str(b))
del a,b,s
print()

#矩陣與純量四則運算
a= np.array([[1,2,3],[4,5,6]])
print(" a=")
print(a)
s = 5
print("s=" + str(s))
b=a+s
print("a+s=")
print(b)
b=a-s
print("a-s=")
print(b)
b=a*s
print("a*s=")
print(b)
b=a/s
print("a/s=")
print(b)
del a,b,s

v=[1 2 3]
s=5
a+s=[6 7 8]
a-s=[-4 -3 -2]
a*s=[ 5 10 15]
a/s=[0.2 0.4 0.6]

 a=
[[1 2 3]
 [4 5 6]]
s=5
a+s=
[[ 6  7  8]
 [ 9 10 11]]
a-s=
[[-4 -3 -2]
 [-1  0  1]]
a*s=
[[ 5 10 15]
 [20 25 30]]
a/s=
[[0.2 0.4 0.6]
 [0.8 1.  1.2]]


In [65]:
#向量與向量四則運算
a = np.array([1,2,3])
print("a=" + str(a))
s = np.array([4, 5, 6])
print("s=" + str(s))
b=a+s
print("a+s=" + str(b))
b=a-s
print("a-s=" + str(b))
b=a*s
print("a*s=" + str(b))
b=a/s
print("a/s=" + str(b))
del a,b,s
print()

#矩陣與矩陣四則運算
a= np.array([[1,2],[3,4]])
print(" a=")
print(a)
s = np.array([[5,6],[7,8]])
print("s=" + str(s))
b=a+s
print("a+s=")
print(b)
b=a-s
print("a-s=")
print(b)
b=a*s
print("a*s=")
print(b)
b=a/s
print("a/s=")
print(b)
del a,b,s

a=[1 2 3]
s=[4 5 6]
a+s=[5 7 9]
a-s=[-3 -3 -3]
a*s=[ 4 10 18]
a/s=[0.25 0.4  0.5 ]

 a=
[[1 2]
 [3 4]]
s=[[5 6]
 [7 8]]
a+s=
[[ 6  8]
 [10 12]]
a-s=
[[-4 -4]
 [-4 -4]]
a*s=
[[ 5 12]
 [21 32]]
a/s=
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [66]:
#向量的點積運算
a = np.array([1, 2,3])
print("a=" + str(a))
s = np.array([4, 5, 6])
print("s=" + str(s))
b = a.dot(s)
print("a.dot(s)=" + str(b))
del a,b,s
print()

#矩陣的點積運算
a= np.array([[1,2],[3,4]])
print(" a=")
print(a)
s = np.array([[5,6],[7,8]])
print("s=" + str(s))
b = a.dot(s)
print("a.dot(s)=" + str(b))
del a,b,s

a=[1 2 3]
s=[4 5 6]
a.dot(s)=32

 a=
[[1 2]
 [3 4]]
s=[[5 6]
 [7 8]]
a.dot(s)=[[19 22]
 [43 50]]


In [67]:
#切割一維陣列元素array[start:end:step]
#使用布林值遮罩索引
a = np.array([14,8,10,11,6,3,18,13,12,9])
print("a="+ str(a))
mask = (a % 3 == 0) #建立布林值陣列
print("mask=" + str(mask))
b = a[mask] #使用布林值陣列取出值
print("a[mask]=" + str(b))
a[a % 3 == 0] = -1 #同時更改多個True索引
print("a[a%3==0]=-1->" + str(a))
del a,b,mask
print()

#切割二維陣列元素array[start:end:step,start1:end1:step1]
a=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print("a=")
print(a)
b=a[[0,1,2],[0,1,0]]#索引[0,0][12
print(" a[[0,1,2],[0,1,0]]=")
print(b)
del a,b
print()

#矩陣使用布林值遮罩索引
a = np.array([[1,2],[3,4],[5,6]])
print(" a=")
print(a)
mask = (a > 2)
print("mask=")
print(mask)
del a,mask

a=[14  8 10 11  6  3 18 13 12  9]
mask=[False False False False  True  True  True False  True  True]
a[mask]=[ 6  3 18 12  9]
a[a%3==0]=-1->[14  8 10 11 -1 -1 -1 13 -1 -1]

a=
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
 a[[0,1,2],[0,1,0]]=
[1 5 7]

 a=
[[1 2]
 [3 4]
 [5 6]]
mask=
[[False False]
 [ True  True]
 [ True  True]]


In [74]:
#使用廣播(自動)執行陣列相加 擴充小矩陣使等式相等
a = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print("a="+ str(a))
print("a 形狀:"+str(a.shape))
b = np.array([1,0,1])
print("b=" + str(b))
print("b形狀:"+str(b.shape))
c =a+b
print("c=a+b")
print("c=",c)
print(a)
del a,b,c

a=[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
a 形狀:(4, 3)
b=[1 0 1]
b形狀:(3,)
c=a+b
c= [[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [78]:
#使用陣列平坦化 numpy.ravel()
a = np.array([[1,2,3],[4,5,6]])
print("a=")
print(a)
b = a.ravel()
print(b)
b = np.ravel(a)
print(b)
del a,b

a=
[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]
[1 2 3 4 5 6]


In [79]:
#更改陣列形狀 array.T | array.transpose()
a = np.array([1,2,3,4,5,6])
print("a=" + str(a))
b =np.reshape(a,(3,2))
print("b=np.reshape(a,(3,2))->")
print(b)
c = b.T
print("c=b.T->")
print(c)
c = b.transpose()
print("c=b.transpose0->")
print(c)
c = np.transpose(b)
print("c=np.transpose(b)->")
print(c)
del a,b,c

a=[1 2 3 4 5 6]
b=np.reshape(a,(3,2))->
[[1 2]
 [3 4]
 [5 6]]
c=b.T->
[[1 3 5]
 [2 4 6]]
c=b.transpose0->
[[1 3 5]
 [2 4 6]]
c=np.transpose(b)->
[[1 3 5]
 [2 4 6]]


In [81]:
#新增陣列的維度 array.newaxis()
a = np.array([1,2,3])
print("a=" + str(a))
b = a[:,np.newaxis]
print("b=a[:,np.newaxis]->")
print(b)
print(b.shape)
b = a[np.newaxis,:]
print("b=a[np.newaxis,:]->")
print(b)
print(b.shape)
del a,b

a=[1 2 3]
b=a[:,np.newaxis]->
[[1]
 [2]
 [3]]
(3, 1)
b=a[np.newaxis,:]->
[[1 2 3]]
(1, 3)


In [82]:
#連接兩個多維陣列 array.concatenate() axis=0直向連接在下方,axis=1橫向連接在右方
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])
c = np.concatenate((a,b))
print("c=np.concatenate(a,b))->")
print(c)
c = np.concatenate((a,b), axis=0)
print("c=np.concatenate((a,b), axis=0)->")
print(c)
c = np.concatenate((a,b), axis=1)
print("c=np.concatenate((a,b), axis=1)->")
print(c)
del a,b,c

c=np.concatenate(a,b))->
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
c=np.concatenate((a,b), axis=0)->
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
c=np.concatenate((a,b), axis=1)->
[[1 2 5 6]
 [3 4 7 8]]


In [ ]:
# 函數 說明
# seed(int) 指定亂數函數的種子數,這是整數值,同一個種子數會產生相同的亂數序列
# random()產生0.0~1.0之間的亂數
# randint(min,max,size) 產生min~max之間的整數亂數,不含max,如果有第3個參數可以產生整數亂數值的陣列
# rand(row.col) 產生亂數值的陣列,第1個參數是一維陣列的尺寸,第2個參數是二維陣列的列與欄
# randn(row,col) 類似rand(),可以產生標準常態分佈的樣本資料,詳見第12章的說明

In [87]:
#三角函數 arrat.sin()
a = np.array([30,45,60])
print(np.sin(a*np.pi/180))
print(np.cos(a*np.pi/180))
print(np.tan(a*np.pi/180))
print()
      
#四捨五入函數 array.around(array.decimals=0(沒有小數))
a = np.array([1.0,5.55, 123, 0.567,25.532])
print("a=" + str(a))
print(np.around(a))
print(np.around(a, decimals= 1))
print(np.around(a, decimals = -1))
del a

[0.5        0.70710678 0.8660254 ]
[0.8660254  0.70710678 0.5       ]
[0.57735027 1.         1.73205081]

a=[  1.      5.55  123.      0.567  25.532]
[  1.   6. 123.   1.  26.]
[  1.    5.6 123.    0.6  25.5]
[  0.  10. 120.   0.  30.]
